[package]
name = "ngit"
version = "0.0.1"
edition = "2021"
description = "cli for code collaboration over nostr"
authors = ["DanConwayDev <DanConwayDev@protonmail.com>"]
readme = "README.md"
homepage = "https://github.com/DanConwayDev/ngit-cli"
repository = "https://github.com/DanConwayDev/ngit-cli"
license = "MIT"
keywords = ["nostr", "git"]
categories = ["command-line-utilities","git"]

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.3.19", features = ["derive"] }
dialoguer = "0.10.4"
directories = "5.0.1"
serde = { version = "1.0.181", features = ["derive"] }
serde_json = "1.0.105"

[dev-dependencies]
assert_cmd = "2.0.12"
duplicate = "1.0.0"
mockall = "0.11.4"
serial_test = "2.0.0"
test_utils = { path = "test_utils" }

[workspace]
members = [
    "test_utils",
]
